"""Coaching graph factory — builds and compiles the LangGraph StateGraph.

Usage:
    graph = build_coaching_graph(interrupt=True)   # production: pauses at present_to_athlete
    graph = build_coaching_graph(interrupt=False)  # tests / direct invocation with human_approved=True

Thread IDs are generated by CoachingService and passed as config["configurable"]["thread_id"].
"""
from __future__ import annotations

from langgraph.checkpoint.memory import MemorySaver
from langgraph.graph import END, START, StateGraph

from .nodes import (
    analyze_profile,
    apply_energy_snapshot,
    build_proposed_plan,
    compute_acwr,
    delegate_specialists,
    detect_conflicts_node,
    finalize_plan,
    merge_recommendations,
    present_to_athlete,
    resolve_conflicts_node,
    revise_plan,
)
from .state import AthleteCoachingState


def _has_critical_conflicts(state: AthleteCoachingState) -> str:
    conflicts = state.get("conflicts_dicts", [])
    has_critical = any(c.get("severity") == "critical" for c in conflicts)
    return "resolve" if has_critical else "build"


def _after_present(state: AthleteCoachingState) -> str:
    return "apply_energy" if state.get("human_approved") else "revise"


def _after_revise(state: AthleteCoachingState) -> str:
    # Count revision messages to enforce max 1 revision
    revision_count = sum(
        1 for m in state.get("messages", [])
        if hasattr(m, "content") and "Révision demandée" in m.content
    )
    if revision_count <= 1:
        return "delegate"
    return "present"


def _after_energy_snapshot(state: AthleteCoachingState) -> str:
    return "finalize"


def build_coaching_graph(interrupt: bool = True):
    """Build and compile the coaching StateGraph with MemorySaver.

    Args:
        interrupt: If True, pauses at present_to_athlete (production).
                   If False, skips interrupt — human_approved must be pre-set in state (tests).
    """
    builder = StateGraph(AthleteCoachingState)

    # Register all nodes
    builder.add_node("analyze_profile", analyze_profile)
    builder.add_node("compute_acwr", compute_acwr)
    builder.add_node("delegate_specialists", delegate_specialists)
    builder.add_node("merge_recommendations", merge_recommendations)
    builder.add_node("detect_conflicts", detect_conflicts_node)
    builder.add_node("resolve_conflicts", resolve_conflicts_node)
    builder.add_node("build_proposed_plan", build_proposed_plan)
    builder.add_node("present_to_athlete", present_to_athlete)
    builder.add_node("revise_plan", revise_plan)
    builder.add_node("apply_energy_snapshot", apply_energy_snapshot)
    builder.add_node("finalize_plan", finalize_plan)

    # Linear pipeline
    builder.add_edge(START, "analyze_profile")
    builder.add_edge("analyze_profile", "compute_acwr")
    builder.add_edge("compute_acwr", "delegate_specialists")
    builder.add_edge("delegate_specialists", "merge_recommendations")
    builder.add_edge("merge_recommendations", "detect_conflicts")
    builder.add_edge("resolve_conflicts", "detect_conflicts")  # loop back after resolution

    # Conflict routing
    builder.add_conditional_edges(
        "detect_conflicts",
        _has_critical_conflicts,
        {"resolve": "resolve_conflicts", "build": "build_proposed_plan"},
    )

    # Plan presentation
    builder.add_edge("build_proposed_plan", "present_to_athlete")

    # Human review routing
    builder.add_conditional_edges(
        "present_to_athlete",
        _after_present,
        {"apply_energy": "apply_energy_snapshot", "revise": "revise_plan"},
    )

    # Revision routing (max 1 revision)
    builder.add_conditional_edges(
        "revise_plan",
        _after_revise,
        {"delegate": "delegate_specialists", "present": "present_to_athlete"},
    )

    # Post-energy snapshot
    builder.add_conditional_edges(
        "apply_energy_snapshot",
        _after_energy_snapshot,
        {"finalize": "finalize_plan"},
    )

    builder.add_edge("finalize_plan", END)

    checkpointer = MemorySaver()
    interrupt_before = ["present_to_athlete"] if interrupt else []

    return builder.compile(
        checkpointer=checkpointer,
        interrupt_before=interrupt_before,
    )
