"""Coaching graph factory — builds and compiles the LangGraph StateGraph.

Usage:
    graph = build_coaching_graph(checkpointer=MemorySaver(), interrupt=True)
    graph = build_coaching_graph(checkpointer=MemorySaver(), interrupt=False)

Thread IDs are generated by CoachingService and passed as config["configurable"]["thread_id"].
"""
from __future__ import annotations

from langgraph.graph import END, START, StateGraph

from .logging import log_node
from .nodes import (
    analyze_profile,
    apply_energy_snapshot,
    build_proposed_plan,
    compute_acwr,
    delegate_specialists,
    detect_conflicts_node,
    finalize_plan,
    merge_recommendations,
    present_to_athlete,
    resolve_conflicts_node,
    revise_plan,
)
from .state import AthleteCoachingState


def _has_critical_conflicts(state: AthleteCoachingState) -> str:
    conflicts = state.get("conflicts_dicts", [])
    has_critical = any(c.get("severity") == "critical" for c in conflicts)
    return "resolve" if has_critical else "build"


def _after_present(state: AthleteCoachingState) -> str:
    return "apply_energy" if state.get("human_approved") else "revise"


def _after_revise(state: AthleteCoachingState) -> str:
    # Count revision messages to enforce max 1 full re-delegation cycle
    revision_count = sum(
        1
        for m in state.get("messages", [])
        if hasattr(m, "content") and "Replanification en cours" in m.content
    )
    if revision_count <= 1:
        return "delegate"
    # Cap reached: rebuild from existing recommendations (no re-delegation)
    return "build"


def build_coaching_graph(*, checkpointer, interrupt: bool = True):
    """Build and compile the coaching StateGraph with caller-provided checkpointer.

    Args:
        checkpointer: LangGraph checkpointer instance (e.g. MemorySaver).
        interrupt: If True, pauses at present_to_athlete (production).
                   If False, skips interrupt — human_approved must be pre-set in state (tests).
    """
    builder = StateGraph(AthleteCoachingState)

    # Register all nodes (wrapped with log_node for structured logging)
    builder.add_node("analyze_profile", log_node(analyze_profile))
    builder.add_node("compute_acwr", log_node(compute_acwr))
    builder.add_node("delegate_specialists", log_node(delegate_specialists))
    builder.add_node("merge_recommendations", log_node(merge_recommendations))
    builder.add_node("detect_conflicts", log_node(detect_conflicts_node))
    builder.add_node("resolve_conflicts", log_node(resolve_conflicts_node))
    builder.add_node("build_proposed_plan", log_node(build_proposed_plan))
    builder.add_node("present_to_athlete", log_node(present_to_athlete))
    builder.add_node("revise_plan", log_node(revise_plan))
    builder.add_node("apply_energy_snapshot", log_node(apply_energy_snapshot))
    builder.add_node("finalize_plan", log_node(finalize_plan))

    # Linear pipeline
    builder.add_edge(START, "analyze_profile")
    builder.add_edge("analyze_profile", "compute_acwr")
    builder.add_edge("compute_acwr", "delegate_specialists")
    builder.add_edge("delegate_specialists", "merge_recommendations")
    builder.add_edge("merge_recommendations", "detect_conflicts")
    builder.add_edge("resolve_conflicts", "detect_conflicts")  # loop back after resolution

    # Conflict routing
    builder.add_conditional_edges(
        "detect_conflicts",
        _has_critical_conflicts,
        {"resolve": "resolve_conflicts", "build": "build_proposed_plan"},
    )

    # Plan presentation
    builder.add_edge("build_proposed_plan", "present_to_athlete")

    # Human review routing
    builder.add_conditional_edges(
        "present_to_athlete",
        _after_present,
        {"apply_energy": "apply_energy_snapshot", "revise": "revise_plan"},
    )

    # Revision routing (max 1 full re-delegation; after that, rebuild from existing recs)
    builder.add_conditional_edges(
        "revise_plan",
        _after_revise,
        {"delegate": "delegate_specialists", "build": "build_proposed_plan"},
    )

    builder.add_edge("apply_energy_snapshot", "finalize_plan")
    builder.add_edge("finalize_plan", END)

    interrupt_before = ["present_to_athlete"] if interrupt else []

    return builder.compile(
        checkpointer=checkpointer,
        interrupt_before=interrupt_before,
    )
