"""Weekly review graph — human-in-the-loop 5-node StateGraph.

Usage:
    graph = build_weekly_review_graph(interrupt=True)   # production: pauses at present_review
    graph = build_weekly_review_graph(interrupt=False)  # tests / direct invocation

Thread IDs are generated by CoachingService and passed as config["configurable"]["thread_id"].
DB session is passed via config["configurable"]["db"].
"""
from __future__ import annotations

import json
import uuid
from datetime import date, timedelta
from typing import Annotated, Any, Literal

from langchain_core.messages import AIMessage, BaseMessage
from langchain_core.runnables import RunnableConfig
from langgraph.checkpoint.memory import MemorySaver
from langgraph.graph import END, START, StateGraph, add_messages
from typing_extensions import TypedDict

from ..core.acwr import compute_acwr as _compute_acwr


# ---------------------------------------------------------------------------
# State
# ---------------------------------------------------------------------------

class WeeklyReviewState(TypedDict):
    """Shared state for the weekly review graph.

    All values are JSON-serializable so that MemorySaver can checkpoint
    state between the present_review interrupt and human confirmation.
    """

    athlete_id: str
    plan_id: str | None
    week_start: str            # ISO date string, e.g. "2026-04-07"
    week_number: int

    # Populated by analyze_actual_vs_planned
    sessions_planned: int
    sessions_completed: int
    completion_rate: float
    actual_hours: float

    # Input for ACWR computation (daily loads, oldest-first)
    load_history: list[float]

    # Populated by compute_new_acwr
    acwr_dict: dict[str, Any] | None

    # Populated by update_athlete_state
    review_summary_dict: dict[str, Any] | None

    # Set by CoachingService.resume_review() before resuming
    human_approved: bool

    # Populated by apply_adjustments
    db_review_id: str | None

    messages: Annotated[list[BaseMessage], add_messages]


# ---------------------------------------------------------------------------
# Node helpers
# ---------------------------------------------------------------------------

def _readiness_from_acwr(acwr: float | None) -> Literal["green", "yellow", "red"] | None:
    if acwr is None:
        return None
    if acwr <= 1.3:
        return "green"
    if acwr <= 1.5:
        return "yellow"
    return "red"


def _build_recommendations(
    acwr: float | None,
    completion_rate: float,
    readiness: str | None,
) -> list[str]:
    recs: list[str] = []
    if readiness == "red":
        recs.append("ACWR > 1.5 — réduire le volume de 20% la semaine prochaine.")
        recs.append("Prioriser le sommeil et la récupération active.")
    elif readiness == "yellow":
        recs.append("ACWR entre 1.3 et 1.5 — maintenir le volume, pas d'augmentation.")
        recs.append("Surveiller les signaux de fatigue (FC repos, humeur, RPE).")
    elif readiness == "green":
        if completion_rate >= 0.9:
            recs.append("Excellente semaine! Tu peux augmenter légèrement le volume (+5–10%).")
        elif completion_rate >= 0.7:
            recs.append("Bonne semaine. Maintenir le volume actuel.")
        else:
            recs.append(
                "Taux de complétion faible — identifier les obstacles et ajuster le planning."
            )
    if completion_rate < 0.5:
        recs.append(
            "Moins de 50% des séances complétées — envisager de réduire la densité du plan."
        )
    return recs


# ---------------------------------------------------------------------------
# Nodes
# ---------------------------------------------------------------------------

def analyze_actual_vs_planned(
    state: WeeklyReviewState,
    config: RunnableConfig,
) -> dict[str, Any]:
    """Node 1 — compare actual vs planned sessions for the review week."""
    db = config["configurable"]["db"]
    athlete_id = state["athlete_id"]
    plan_id = state["plan_id"]
    week_start_str = state["week_start"]

    try:
        week_start = date.fromisoformat(week_start_str)
    except ValueError:
        week_start = date.today() - timedelta(days=date.today().weekday())

    # Lazy import via app. path to avoid SQLAlchemy double-table-registration.
    import importlib
    importlib.import_module("app.models.schemas")  # registers V3 SA models first
    _db_models = importlib.import_module("app.db.models")
    SessionLogModel = _db_models.SessionLogModel
    TrainingPlanModel = _db_models.TrainingPlanModel

    # Count planned sessions for this week from the plan's weekly_slots_json
    sessions_planned = 0
    if plan_id:
        plan = db.get(TrainingPlanModel, plan_id)
        if plan:
            try:
                slots_data = json.loads(plan.weekly_slots_json)
            except Exception:
                slots_data = []
            for week_block in slots_data:
                ws = week_block.get("week_start")
                if ws:
                    try:
                        if date.fromisoformat(ws) == week_start:
                            sessions_planned = len(week_block.get("sessions", []))
                            break
                    except ValueError:
                        pass

    # Count completed sessions (non-skipped, has actual_duration_min)
    sessions_completed = (
        db.query(SessionLogModel)
        .filter(
            SessionLogModel.athlete_id == athlete_id,
            SessionLogModel.skipped == False,  # noqa: E712
            SessionLogModel.actual_duration_min.isnot(None),
        )
        .count()
    )

    completion_rate = (
        sessions_completed / sessions_planned if sessions_planned > 0 else 0.0
    )

    # Estimate actual hours: assume avg 60-min sessions if no duration data
    try:
        duration_rows = (
            db.query(SessionLogModel.actual_duration_min)
            .filter(
                SessionLogModel.athlete_id == athlete_id,
                SessionLogModel.skipped == False,  # noqa: E712
                SessionLogModel.actual_duration_min.isnot(None),
            )
            .all()
        )
        total_minutes = sum(r.actual_duration_min for r in duration_rows if r.actual_duration_min)
    except Exception:
        total_minutes = sessions_completed * 60
    actual_hours = round(total_minutes / 60.0, 2)

    return {
        "sessions_planned": sessions_planned,
        "sessions_completed": sessions_completed,
        "completion_rate": round(completion_rate, 4),
        "actual_hours": actual_hours,
        "messages": [
            AIMessage(
                content=(
                    f"Analyse semaine {state['week_number']}: "
                    f"{sessions_completed}/{sessions_planned} séances, "
                    f"{round(completion_rate * 100, 1)}% complétion."
                )
            )
        ],
    }


def compute_new_acwr(
    state: WeeklyReviewState,
    config: RunnableConfig,
) -> dict[str, Any]:
    """Node 2 — recompute ACWR from load history."""
    load_history = state.get("load_history", [])

    acwr_dict: dict[str, Any] | None = None
    if load_history:
        try:
            acwr_result = _compute_acwr(load_history)
            acwr_dict = {
                "ratio": acwr_result.ratio,
                "status": acwr_result.status.value,
                "acute_7d": acwr_result.acute_7d,
                "chronic_28d": acwr_result.chronic_28d,
                "max_safe_weekly_load": acwr_result.max_safe_weekly_load,
            }
        except Exception:
            acwr_dict = None

    return {
        "acwr_dict": acwr_dict,
        "messages": [
            AIMessage(
                content=(
                    f"ACWR calculé: {acwr_dict['ratio']:.2f} ({acwr_dict['status']})"
                    if acwr_dict
                    else "ACWR: données insuffisantes."
                )
            )
        ],
    }


def update_athlete_state(
    state: WeeklyReviewState,
    config: RunnableConfig,
) -> dict[str, Any]:
    """Node 3 — assemble review summary dict for presentation."""
    acwr_dict = state.get("acwr_dict")
    acwr_ratio = acwr_dict["ratio"] if acwr_dict else None
    readiness = _readiness_from_acwr(acwr_ratio)
    completion_rate = state.get("completion_rate", 0.0)
    recommendations = _build_recommendations(acwr_ratio, completion_rate, readiness)

    review_summary_dict: dict[str, Any] = {
        "week_number": state["week_number"],
        "week_start": state["week_start"],
        "sessions_planned": state.get("sessions_planned", 0),
        "sessions_completed": state.get("sessions_completed", 0),
        "completion_rate": completion_rate,
        "actual_hours": state.get("actual_hours", 0.0),
        "acwr": acwr_ratio,
        "readiness": readiness,
        "recommendations": recommendations,
    }

    return {
        "review_summary_dict": review_summary_dict,
        "messages": [
            AIMessage(
                content=(
                    f"Résumé prêt. Readiness: {readiness or 'N/A'}. "
                    f"{len(recommendations)} recommandation(s)."
                )
            )
        ],
    }


def present_review(
    state: WeeklyReviewState,
    config: RunnableConfig,
) -> dict[str, Any]:
    """Node 4 — interrupt gate. No-op; interrupt_before handles the pause.

    When interrupted, CoachingService.resume_review() injects human_approved=True
    and resumes. This node then runs as a pass-through before apply_adjustments.
    """
    return {}


def apply_adjustments(
    state: WeeklyReviewState,
    config: RunnableConfig,
) -> dict[str, Any]:
    """Node 5 — persist WeeklyReviewModel to DB after human approval."""
    if not state.get("human_approved"):
        # Athlete declined — no DB write, just record the decision
        return {
            "db_review_id": None,
            "messages": [AIMessage(content="Révision hebdomadaire annulée par l'athlète.")],
        }

    db = config["configurable"]["db"]
    athlete_id = state["athlete_id"]
    plan_id = state["plan_id"]
    summary = state.get("review_summary_dict") or {}
    acwr_dict = state.get("acwr_dict")

    import importlib
    importlib.import_module("app.models.schemas")  # registers V3 SA models first
    _db_models = importlib.import_module("app.db.models")
    WeeklyReviewModel = _db_models.WeeklyReviewModel

    try:
        week_start = date.fromisoformat(state["week_start"])
    except ValueError:
        week_start = date.today() - timedelta(days=date.today().weekday())

    review_id = str(uuid.uuid4())
    review = WeeklyReviewModel(
        id=review_id,
        athlete_id=athlete_id,
        plan_id=plan_id,
        week_start=week_start,
        week_number=state.get("week_number", 1),
        planned_hours=0.0,
        actual_hours=summary.get("actual_hours"),
        acwr=acwr_dict["ratio"] if acwr_dict else None,
        adjustment_applied=None,
        readiness_score=None,
        athlete_comment="",
        results_json=json.dumps(summary),
    )
    db.add(review)
    db.commit()
    db.refresh(review)

    return {
        "db_review_id": review_id,
        "messages": [
            AIMessage(
                content=(
                    f"Révision semaine {state.get('week_number', 1)} enregistrée "
                    f"(id={review_id[:8]}…)."
                )
            )
        ],
    }


# ---------------------------------------------------------------------------
# Graph factory
# ---------------------------------------------------------------------------

def build_weekly_review_graph(interrupt: bool = True):
    """Build and compile the weekly review StateGraph with MemorySaver.

    Args:
        interrupt: If True, pauses at present_review (production).
                   If False, skips interrupt — human_approved must be pre-set in state (tests).
    """
    builder: StateGraph = StateGraph(WeeklyReviewState)

    builder.add_node("analyze_actual_vs_planned", analyze_actual_vs_planned)
    builder.add_node("compute_new_acwr", compute_new_acwr)
    builder.add_node("update_athlete_state", update_athlete_state)
    builder.add_node("present_review", present_review)
    builder.add_node("apply_adjustments", apply_adjustments)

    # Linear pipeline
    builder.add_edge(START, "analyze_actual_vs_planned")
    builder.add_edge("analyze_actual_vs_planned", "compute_new_acwr")
    builder.add_edge("compute_new_acwr", "update_athlete_state")
    builder.add_edge("update_athlete_state", "present_review")
    builder.add_edge("present_review", "apply_adjustments")
    builder.add_edge("apply_adjustments", END)

    checkpointer = MemorySaver()
    interrupt_before = ["present_review"] if interrupt else []

    return builder.compile(
        checkpointer=checkpointer,
        interrupt_before=interrupt_before,
    )
