"""add fatigue snapshot unique athlete date

Revision ID: 37168fe9feab
Revises: d54fb4efd721
Create Date: 2026-04-05 23:37:13.894478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37168fe9feab'
down_revision: Union[str, Sequence[str], None] = 'd54fb4efd721'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'fatigue_snapshots', ['athlete_id', 'snapshot_date'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'fatigue_snapshots', type_='unique')
    # ### end Alembic commands ###
