"""initial schema

Revision ID: 55a168264480
Revises: 
Create Date: 2026-04-04 17:43:21.258594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '55a168264480'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('athletes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('sex', sa.String(length=1), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=False),
    sa.Column('height_cm', sa.Float(), nullable=False),
    sa.Column('body_fat_percent', sa.Float(), nullable=True),
    sa.Column('resting_hr', sa.Integer(), nullable=True),
    sa.Column('max_hr_measured', sa.Integer(), nullable=True),
    sa.Column('profile_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('available_days', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('athlete_states',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('athlete_id', sa.UUID(), nullable=False),
    sa.Column('macrocycle_phase', sa.Enum('base_building', 'build', 'peak', 'taper', 'race', 'transition', name='macrocyclephase'), nullable=False),
    sa.Column('mesocycle_week', sa.Integer(), nullable=False),
    sa.Column('target_event_date', sa.Date(), nullable=True),
    sa.Column('running_profile', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('lifting_profile', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('swimming_profile', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('biking_profile', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('nutrition_profile', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('weekly_km_running', sa.Float(), nullable=False),
    sa.Column('weekly_sessions_lifting', sa.Integer(), nullable=False),
    sa.Column('weekly_km_biking', sa.Float(), nullable=False),
    sa.Column('weekly_km_swimming', sa.Float(), nullable=False),
    sa.Column('total_training_hours', sa.Float(), nullable=False),
    sa.Column('completion_rate_4weeks', sa.Float(), nullable=True),
    sa.Column('nutrition_adherence_7days', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athletes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_athlete_states_athlete_id'), 'athlete_states', ['athlete_id'], unique=False)
    op.create_table('decision_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('athlete_id', sa.UUID(), nullable=False),
    sa.Column('conflict_id', sa.String(length=50), nullable=False),
    sa.Column('situation', sa.Text(), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=False),
    sa.Column('alternatives_presented', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('user_choice', sa.Text(), nullable=True),
    sa.Column('final_decision', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('awaiting', 'confirmed', 'overridden', name='decisionstatus'), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('biometric_context', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athletes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decision_logs_athlete_id'), 'decision_logs', ['athlete_id'], unique=False)
    op.create_table('fatigue_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('athlete_id', sa.UUID(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('hrv_rmssd', sa.Float(), nullable=True),
    sa.Column('hr_rest', sa.Integer(), nullable=True),
    sa.Column('sleep_hours', sa.Float(), nullable=True),
    sa.Column('sleep_quality_subjective', sa.Integer(), nullable=True),
    sa.Column('acwr_global', sa.Float(), nullable=True),
    sa.Column('acwr_running', sa.Float(), nullable=True),
    sa.Column('acwr_lifting', sa.Float(), nullable=True),
    sa.Column('acwr_biking', sa.Float(), nullable=True),
    sa.Column('weekly_fatigue_score', sa.Float(), nullable=True),
    sa.Column('cns_load_7day_avg', sa.Float(), nullable=True),
    sa.Column('fatigue_by_muscle', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('recovery_score', sa.Float(), nullable=True),
    sa.Column('readiness_color', sa.Enum('green', 'yellow', 'red', name='readinesscolor'), nullable=True),
    sa.Column('fatigue_subjective', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athletes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fatigue_snapshots_athlete_id'), 'fatigue_snapshots', ['athlete_id'], unique=False)
    op.create_index(op.f('ix_fatigue_snapshots_snapshot_date'), 'fatigue_snapshots', ['snapshot_date'], unique=False)
    op.create_table('lifting_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('athlete_id', sa.UUID(), nullable=False),
    sa.Column('hevy_title', sa.String(length=200), nullable=False),
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('total_volume_kg', sa.Float(), nullable=True),
    sa.Column('total_sets', sa.Integer(), nullable=True),
    sa.Column('avg_rpe', sa.Float(), nullable=True),
    sa.Column('estimated_tss', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('hevy_workout_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athletes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lifting_sessions_athlete_id'), 'lifting_sessions', ['athlete_id'], unique=False)
    op.create_index(op.f('ix_lifting_sessions_session_date'), 'lifting_sessions', ['session_date'], unique=False)
    op.create_table('run_activities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('athlete_id', sa.UUID(), nullable=False),
    sa.Column('strava_activity_id', sa.String(length=100), nullable=True),
    sa.Column('activity_date', sa.Date(), nullable=False),
    sa.Column('activity_type', sa.String(length=50), nullable=False),
    sa.Column('distance_km', sa.Float(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('avg_pace_sec_per_km', sa.Float(), nullable=True),
    sa.Column('avg_hr', sa.Integer(), nullable=True),
    sa.Column('max_hr', sa.Integer(), nullable=True),
    sa.Column('elevation_gain_m', sa.Float(), nullable=True),
    sa.Column('estimated_tss', sa.Float(), nullable=True),
    sa.Column('trimp', sa.Float(), nullable=True),
    sa.Column('strava_raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athletes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_run_activities_activity_date'), 'run_activities', ['activity_date'], unique=False)
    op.create_index(op.f('ix_run_activities_athlete_id'), 'run_activities', ['athlete_id'], unique=False)
    op.create_index(op.f('ix_run_activities_strava_activity_id'), 'run_activities', ['strava_activity_id'], unique=True)
    op.create_table('weekly_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('athlete_id', sa.UUID(), nullable=False),
    sa.Column('week_start_date', sa.Date(), nullable=False),
    sa.Column('week_end_date', sa.Date(), nullable=False),
    sa.Column('macrocycle_phase', sa.Enum('base_building', 'build', 'peak', 'taper', 'race', 'transition', name='macrocyclephase'), nullable=False),
    sa.Column('mesocycle_week', sa.Integer(), nullable=False),
    sa.Column('plan_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('constraint_matrix', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_confirmed', sa.Boolean(), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_modifications', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('completion_rate', sa.Float(), nullable=True),
    sa.Column('sessions_planned', sa.Integer(), nullable=True),
    sa.Column('sessions_completed', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athletes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weekly_plans_athlete_id'), 'weekly_plans', ['athlete_id'], unique=False)
    op.create_index(op.f('ix_weekly_plans_week_start_date'), 'weekly_plans', ['week_start_date'], unique=False)
    op.create_table('lifting_sets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('exercise_title', sa.String(length=200), nullable=False),
    sa.Column('superset_id', sa.String(length=50), nullable=True),
    sa.Column('set_index', sa.Integer(), nullable=False),
    sa.Column('set_type', sa.Enum('normal', 'warmup', 'dropset', 'failure', name='settype'), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('reps', sa.Integer(), nullable=True),
    sa.Column('rpe', sa.Float(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('distance_km', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['lifting_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lifting_sets_exercise_title'), 'lifting_sets', ['exercise_title'], unique=False)
    op.create_index(op.f('ix_lifting_sets_session_id'), 'lifting_sets', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lifting_sets_session_id'), table_name='lifting_sets')
    op.drop_index(op.f('ix_lifting_sets_exercise_title'), table_name='lifting_sets')
    op.drop_table('lifting_sets')
    op.drop_index(op.f('ix_weekly_plans_week_start_date'), table_name='weekly_plans')
    op.drop_index(op.f('ix_weekly_plans_athlete_id'), table_name='weekly_plans')
    op.drop_table('weekly_plans')
    op.drop_index(op.f('ix_run_activities_strava_activity_id'), table_name='run_activities')
    op.drop_index(op.f('ix_run_activities_athlete_id'), table_name='run_activities')
    op.drop_index(op.f('ix_run_activities_activity_date'), table_name='run_activities')
    op.drop_table('run_activities')
    op.drop_index(op.f('ix_lifting_sessions_session_date'), table_name='lifting_sessions')
    op.drop_index(op.f('ix_lifting_sessions_athlete_id'), table_name='lifting_sessions')
    op.drop_table('lifting_sessions')
    op.drop_index(op.f('ix_fatigue_snapshots_snapshot_date'), table_name='fatigue_snapshots')
    op.drop_index(op.f('ix_fatigue_snapshots_athlete_id'), table_name='fatigue_snapshots')
    op.drop_table('fatigue_snapshots')
    op.drop_index(op.f('ix_decision_logs_athlete_id'), table_name='decision_logs')
    op.drop_table('decision_logs')
    op.drop_index(op.f('ix_athlete_states_athlete_id'), table_name='athlete_states')
    op.drop_table('athlete_states')
    op.drop_table('athletes')
    # ### end Alembic commands ###
