"""add connector credentials

Revision ID: d54fb4efd721
Revises: 55a168264480
Create Date: 2026-04-05 14:31:13.547695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd54fb4efd721'
down_revision: Union[str, Sequence[str], None] = '55a168264480'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connector_credentials',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('athlete_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('api_key', sa.Text(), nullable=True),
    sa.Column('external_athlete_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athletes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('athlete_id', 'provider')
    )
    op.create_index(op.f('ix_connector_credentials_athlete_id'), 'connector_credentials', ['athlete_id'], unique=False)
    op.create_index(op.f('ix_lifting_sessions_hevy_workout_id'), 'lifting_sessions', ['hevy_workout_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lifting_sessions_hevy_workout_id'), table_name='lifting_sessions')
    op.drop_index(op.f('ix_connector_credentials_athlete_id'), table_name='connector_credentials')
    op.drop_table('connector_credentials')
    # ### end Alembic commands ###
